drop table if exists genres, mpa_rating, users, films, films_genre, likes, friends;

create table if not exists genres
(
    genre_id int primary key,
    name     varchar(20)
);

create table if not exists mpa_rating
(
    mpa_id int primary key,
    name   varchar(5)
);

create table if not exists users
(
    user_id  int generated by default as identity primary key,
    email    varchar(30),
    login    varchar(30),
    name     varchar(20),
    birthday date
);

create table if not exists films
(
    film_id     int generated by default as identity primary key,
    name        varchar(20),
    description varchar(200),
    releaseDate date,
    duration    int,
    mpa_id     int references mpa_rating (mpa_id)
);

create table if not exists films_genre
(
    film_id  int references films (film_id),
    genre_id int references genres (genre_id)
);

create table if not exists likes
(
    user_id int references users (user_id),
    film_id int references films (film_id)
);

create table if not exists friends
(
    user_id   int references users (user_id),
    friend_id int references users (user_id),
    status    int
);